name: release
on:
  push:
    tags:
    - "v*"
jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux']
        arch: ['amd64','arm']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - run: go mod download
      - name: Build Client
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run : |
          go build -o pushprox-client
           -ldflags "-X main.version=$(git describe --tags --abbrev=0) -X main.revision=$(git rev-parse --short HEAD)"
           ./cmd/client/main.go
      - name: Build Proxy
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run : |
          go build -o pushprox-proxy 
           -ldflags "-X main.version=$(git describe --tags --abbrev=0) -X main.revision=$(git rev-parse --short HEAD)"
           ./cmd/proxy/main.go ./cmd/proxy/coordinator.go
      - name: Create Package
        run: tar czvf pushprox-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ./pushprox-client ./pushprox-proxy
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: pushprox-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

